adbc push ksocket.ko /sdcard/dfv_client/
adbc push dfvclient.ko /sdcard/dfv_client/
adbc push dfvclient_network.ko /sdcard/dfv_client/
adbc push scripts/load_client_android.sh /sdcard/dfv_client/
adbc push scripts/enable_audio_client_android.sh /sdcard/dfv_client/
adbc push scripts/enable_accelerometer_client_android.sh /sdcard/dfv_client/
adbc push scripts/enable_camera_client_android.sh /sdcard/dfv_client/
adbc push scripts/disable_audio_client_android.sh /sdcard/dfv_client/
adbc push scripts/disable_accelerometer_client_android.sh /sdcard/dfv_client/
adbc push scripts/disable_camera_client_android.sh /sdcard/dfv_client/
adbc push scripts/emulate_disconnect_accelerometer_client.sh /sdcard/dfv_client/
adbc push scripts/emulate_reconnect_accelerometer_client.sh /sdcard/dfv_client/
