adbs push ksocket.ko /sdcard/dfv_server/
adbs push dfvserver.ko /sdcard/dfv_server/
adbs push dfvserver_network.ko /sdcard/dfv_server/
adbs push scripts/load_server_android.sh /sdcard/dfv_server/
adbs push scripts/enable_audio_server_android.sh /sdcard/dfv_server/
adbs push scripts/enable_accelerometer_server_android.sh /sdcard/dfv_server/
adbs push scripts/enable_camera_server_android.sh /sdcard/dfv_server/
adbs push scripts/disable_audio_server_android.sh /sdcard/dfv_server/
adbs push scripts/disable_accelerometer_server_android.sh /sdcard/dfv_server/
adbs push scripts/disable_camera_server_android.sh /sdcard/dfv_server/
